#!/usr/bin/python3
import pandas as pd

train = pd.read_pickle("../data/atis/train.pickle")
dev = pd.read_pickle("../data/atis/dev.pickle")
dataset = "atis"

# get train bins (to tune on dev)
dev_share = int(len(dev) / 6)
train_bin6 = train.sample(3983, random_state=1337)
train_bin5 = train_bin6.sample(4000 - dev_share * 5, random_state=1337)
train_bin4 = train_bin5.sample(3000 - dev_share * 4, random_state=1337)
train_bin3 = train_bin4.sample(2000 - dev_share * 3, random_state=1337)
train_bin2 = train_bin3.sample(1000 - dev_share * 2, random_state=1337)
train_bin1 = train_bin2.sample(500 - dev_share, random_state=1337)
print("train bins")
print(len(train_bin6))
print(len(train_bin5))
print(len(train_bin4))
print(len(train_bin3))
print(len(train_bin2))
print(len(train_bin1))
train_bin6.to_pickle("../data/%s/random_bins/train/train_bin6.pickle" % dataset)
train_bin5.to_pickle("../data/%s/random_bins/train/train_bin5.pickle" % dataset)
train_bin4.to_pickle("../data/%s/random_bins/train/train_bin4.pickle" % dataset)
train_bin3.to_pickle("../data/%s/random_bins/train/train_bin3.pickle" % dataset)
train_bin2.to_pickle("../data/%s/random_bins/train/train_bin2.pickle" % dataset)
train_bin1.to_pickle("../data/%s/random_bins/train/train_bin1.pickle" % dataset)

# get dev bins (to have train_dev bins for final training), after tuning
dev_bin6 = dev.sample(995, random_state=1337)
dev_bin5 = dev_bin6.sample(dev_share * 5, random_state=1337)
dev_bin4 = dev_bin5.sample(dev_share * 4, random_state=1337)
dev_bin3 = dev_bin4.sample(dev_share * 3, random_state=1337)
dev_bin2 = dev_bin3.sample(dev_share * 2, random_state=1337)
dev_bin1 = dev_bin2.sample(dev_share, random_state=1337)
print("dev bins")
print(len(dev_bin6))
print(len(dev_bin5))
print(len(dev_bin4))
print(len(dev_bin3))
print(len(dev_bin2))
print(len(dev_bin1))
dev_bin6.to_pickle("../data/%s/random_bins/dev/dev_bin6.pickle" % dataset)
dev_bin5.to_pickle("../data/%s/random_bins/dev/dev_bin5.pickle" % dataset)
dev_bin4.to_pickle("../data/%s/random_bins/dev/dev_bin4.pickle" % dataset)
dev_bin3.to_pickle("../data/%s/random_bins/dev/dev_bin3.pickle" % dataset)
dev_bin2.to_pickle("../data/%s/random_bins/dev/dev_bin2.pickle" % dataset)
dev_bin1.to_pickle("../data/%s/random_bins/dev/dev_bin1.pickle" % dataset)

print("train_dev_bins")
# form train_dev bins
train_dev_bin6 = pd.concat([train_bin6, dev_bin6])
train_dev_bin5 = pd.concat([train_bin5, dev_bin5])
train_dev_bin4 = pd.concat([train_bin4, dev_bin4])
train_dev_bin3 = pd.concat([train_bin3, dev_bin3])
train_dev_bin2 = pd.concat([train_bin2, dev_bin2])
train_dev_bin1 = pd.concat([train_bin1, dev_bin1])
print(len(train_dev_bin6))
print(len(train_dev_bin5))
print(len(train_dev_bin4))
print(len(train_dev_bin3))
print(len(train_dev_bin2))
print(len(train_dev_bin1))
train_dev_bin6.to_pickle("../data/%s/random_bins/train_dev/train_dev_bin6.pickle" % dataset)
train_dev_bin5.to_pickle("../data/%s/random_bins/train_dev/train_dev_bin5.pickle" % dataset)
train_dev_bin4.to_pickle("../data/%s/random_bins/train_dev/train_dev_bin4.pickle" % dataset)
train_dev_bin3.to_pickle("../data/%s/random_bins/train_dev/train_dev_bin3.pickle" % dataset)
train_dev_bin2.to_pickle("../data/%s/random_bins/train_dev/train_dev_bin2.pickle" % dataset)
train_dev_bin1.to_pickle("../data/%s/random_bins/train_dev/train_dev_bin1.pickle" % dataset)
